apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nvflare.fullname" . }}-efs
  labels:
    {{- include "nvflare.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.efsStorageClass.storageRequest }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "nvflare.fullname" . }}
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsStorageClass.fileSystemId }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nvflare.fullname" . }}-persist-efs
  labels:
    {{- include "nvflare.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.efsStorageClass.storageRequest }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "nvflare.fullname" . }}
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsStorageClass.fileSystemId }}
